---

  - name: install nginx repo
    yum: pkg=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm state=installed

  - name: install nginx
    yum: pkg=nginx state=installed
    notify: restart nginx

  - name: enable nxinx at boot
    service: name=nginx enabled=true

  - name: delete pre-installed sites
    file: dest=/etc/nginx/conf.d/{{ item }} state=absent
    with_items:
      - default.conf
      - example_ssl.conf
    notify: restart nginx
